### PR TITLE
Deploy storybook

### PR DESCRIPTION
**Pull request by dvdherron**
## Steps to test/reproduce
As of now  . . .
- `yarn run deploy-storybook` to deploy

_Please explain how to best reproduce the issue and/or test the changes locally (including the pages/URLs/views/states to review)._

### CODE REVIEW

**Comment by dvdherron** [comment]
[Deployment](https://trello.com/c/InhKSqgR/103-deployment)

**Comment by dvdherron** [comment]
@jgerigmeyer reopened here

**Comment by dvdherron** [comment]
History: https://github.com/oddbird/Metecho/pull/1258

**Comment by dvdherron** [comment]
For context, the previous PR was deleted when I ran this command as a test:

> root@4c737021651c:/app# yarn run deploy-storybook -- --ci --branch=deploy-storybook --out=./storybook-static
yarn run v1.22.5
> warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
> $ storybook-to-ghpages -d storybook-static --ci --branch=deploy-storybook --out=./storybook-static
> => Getting the git remote URL
>    executing: git config --get remote.origin.url
> => Building storybook for: metecho
>    executing: npm run build-storybook -- -o ./storybook-static
>    executing: git init
>    executing: git checkout -b master
>    executing: git config user.name "GH Pages Bot"
>    executing: git config user.email "hello@ghbot.com"
>    executing: git config commit.gpgsign false
>    executing: git checkout -b "master"
> => Deploying from source branch: "master"
>    executing: git add .
>    executing: git commit -m "Deploy Storybook to GitHub Pages"
> => Deploying storybook
>    executing: git push --force --quiet https://github.com/oddbird/Metecho.git master:deploy-storybook
> => Storybook deployed to: https://rawgit.com/oddbird/Metecho/deploy-storybook/index.html
> Done in 200.45s.

**Review by jgerigmeyer — APPROVED** [review]

**Comment by dvdherron** [comment]
[MetaDeploy: deploy storybook](https://trello.com/c/FqIQm6zw/104-metadeploy-deploy-storybook)

**Pull request merged**
