### PR TITLE
consistent capitalization of core objects/terms

### PR DESCRIPTION
**Pull request by dvdherron**
## Description
- Makes core terms (Epic, Task, Project, Scratch/Dev/Test Org, Project etc) consistent in how they are capitalized. 
- Also fixes some wayward punctuation that falls outside of quotation marks ( e.g. "A wayward period". )

## Steps to test/reproduce
- with the environment running search for the above terms
- Otherwise, look throughout the running project (toast messages, modals, etc.) to see updated capitalization
_Please explain how to best reproduce the issue and/or test the changes locally (including the pages/URLs/views/states to review)._

## Show me
_Provide screenshots/animated gifs/videos if necessary._

### CODE REVIEW

**Comment by dvdherron** [comment]
[I want consistent capitalization of core objects/terms (e.g. Project, Task, Scratch Org).](https://trello.com/c/J04dg5Yi/293-i-want-consistent-capitalization-of-core-objects-terms-eg-project-task-scratch-org)

**Comment by dvdherron** [comment]
I think the easiest way to review this will be to search for terms in `locales/en/translations.json`? Most of the changes will be there.

**Review by jgerigmeyer — APPROVED** [review]

**Comment by jgerigmeyer** [comment]
@SondraE or @stacyk, does one of you want to do a brief sanity-check on the basics of this PR? That is, are these the right items to capitalize in this way?

**Comment by SondraE** [comment]
@jgerigmeyer @stacyk I haven't ever run the Metecho environment. Not sure how time consuming that is to set up. Happy to let Stacy review.

To your question about whether these are the right items to capitalize, the ones I proposed were: 

- Project
- Epic
- Task
- [Scratch/Dev/Test] Org
- Collaborator
- Developer
- Tester
- Statuses 

My goal with this capitalization is to emphasize the core objects as a clue about what to pay attention to in Metecho since there is so much to see and learn. My hope is that people will look for, recognize, and orient themselves around these objects wherever they appear in Metecho. 

If it feels like too many words are emphasized, we could consider removing the capital letter from the statuses. They are an important clue as to next steps, but they're not objects.

If I remember right, I had originally started capitalizing these objects just in the self-guided tour and the walkthroughs. I'll be curious to hear, @stacyk, whether you think it works to have them capitalized everywhere they occur.

**Comment by jgerigmeyer** [comment]
> To your question about whether these are the right items to capitalize, the ones I proposed were:

@SondraE Okay, I think what we did matches what you outlined above. 👍

**Review by jgerigmeyer — APPROVED** [review]
👏

**Comment by jgerigmeyer** [comment]
@stacyk I think this is waiting on functional review from you when you have a few minutes.

**Review by stacyk — APPROVED** [review]
Everything here looks great!

**Review by stacyk — APPROVED** [review]
Everything here looks great!

**Pull request merged**
