### PR TITLE
Allow converting Project playground org into new Task dev org.

### PR DESCRIPTION
**Pull request by jgerigmeyer**
## Steps to test/reproduce
_Please explain how to best reproduce the issue and/or test the changes locally (including the pages/URLs/views/states to review)._

- Create a *Project* scratch org
- Make changes in the org
- Click "contribute" btn on org
- Select either "Create a new Epic and Task" or "Create a new Task with no Epic"
- Click "Contribute" btn
- If you selected "new epic and task":
  - fill out create epic form and submit
  - fill out create task form and submit
  - see the new task with your org as the Dev Org (and you assigned as the Dev), then the "retrieve changes" modal opens
- If you selected "new task with no epic":
  - fill out create task form and submit
  - see the new task with your org as the Dev Org (and you assigned as the Dev), then the "retrieve changes" modal opens

## Show me
_Provide screenshots/animated gifs/videos if necessary._

Screen Shot 2021-09-09 at 12 36 28 PM
Screen Shot 2021-09-09 at 12 36 36 PM
Screen Shot 2021-09-09 at 12 36 42 PM
Screen Shot 2021-09-09 at 12 36 53 PM

### CODE REVIEW

**Comment by jgerigmeyer** [comment]
[I want to convert a project scratch org into a new epic or task.](https://trello.com/c/Y5nDmvPd/231-i-want-to-convert-a-project-scratch-org-into-a-new-epic-or-task)

**Review by jerivas — APPROVED** [review]
Functional review went well! The only thing I noticed is a message appears before creating the Project Scratch Org stating:

> You will not be able to retrieve any changes made in this Scratch Org.

We could explain that the org can be converted later to contribute work.

**Comment by jgerigmeyer** [comment]
> The only thing I noticed is a message appears before creating the Project Scratch Org stating:
> 
> > You will not be able to retrieve any changes made in this Scratch Org.

@jerivas Good catch! Fixed in https://github.com/oddbird/Metecho/pull/1467/commits/100bdb3718c4cc2dd2d7d01688f9f1e630c05b47

**Comment by jgerigmeyer** [comment]
@stacyk No style changes here, but this is ready for your functional review.

@oluoluoxenfree I think it might be helpful for us to do code review together on this?

**Comment by stacyk** [comment]
Since you mentioned that this story doesn't have any style changes, I'm wondering if we should make a new story for this layout issue or is this something that should happen in this PR @jgerigmeyer?
Screen Shot 2021-09-14 at 2 22 41 PM

**Comment by jgerigmeyer** [comment]
> Since you mentioned that this story doesn't have any style changes, I'm wondering if we should make a new story for this layout issue or is this something that should happen in this PR @jgerigmeyer?

@stacyk That should be a new story. It's an existing/known "bug" on all orgs when they get narrow -- mostly an issue for project orgs that live in the sidebar, but also task dev/test orgs at narrower screen widths.

**Review by stacyk — APPROVED** [review]
The functionality worked great for me. 

The mention of Epic in this screen is a little unclear (as in, if one should go back and select Epic instead but there isn't a back button, or if you should convert to an Epic in the future) but the solution would be done in a different story (leaving this comment here since it was only noticeable from the context of going through the steps of project scratch org -> task).
 
Screen Shot 2021-09-14 at 2 26 02 PM

**Comment by jgerigmeyer** [comment]
> The mention of Epic in this screen is a little unclear (as in, if one should go back and select Epic instead but there isn't a back button, or if you should convert to an Epic in the future) but the solution would be done in a different story (leaving this comment here since it was only noticeable from the context of going through the steps of project scratch org -> task).

@stacyk Would it be helpful to say "first create an Epic"? Or make "create an Epic" link to the create-epic modal? Or what would you suggest? cc @SondraE

**Comment by SondraE** [comment]
@jgerigmeyer @stacyk 
I don't believe we need to mention epics in that 'create a task to contribute...' modal description since the person presumably just made the decision to "create a task with no epic" in a previous modal. If they change their mind, they can immediately create an epic from their new task detail page. (Unfortunately, if they create 2 separate epic-less tasks and then want to group them together in the same epic, there is no way to do that, but that's a different story.)

**Comment by stacyk** [comment]
> @jgerigmeyer @stacyk
> I don't believe we need to mention epics in that 'create a task to contribute...' modal description since the person presumably just made the decision to "create a task with no epic" in a previous modal. If they change their mind, they can immediately create an epic from their new task detail page. (Unfortunately, if they create 2 separate epic-less tasks and then want to group them together in the same epic, there is no way to do that, but that's a different story.)

Agreed. Better to remove it since the person just confirmed. Either that or a back button if they want to change their mind but I don't think we need to add that for this fix.

**Comment by jgerigmeyer** [comment]
> I don't believe we need to mention epics in that 'create a task to contribute...' modal description since the person presumably just made the decision to "create a task with no epic" in a previous modal.

@SondraE Okay. So we'll still show this text as-is if the user clicked "Create Task" from the project detail page, but we won't show it if they got here from "Contribute Work" on a scratch org -- ]]correct?

> If they change their mind, they can immediately create an epic from their new task detail page.

@SondraE How? We don't have a way to create a new Epic from an existing Task. So once they make this selection, they're locked in.

> Either that or a back button if they want to change their mind but I don't think we need to add that for this fix.

@stacyk That seems pretty low priority to me, since they can easily cancel and start again. 🤷

**Pull request merged**
