### PR TITLE
[guided tour] Add Help walkthrough

### PR DESCRIPTION
**Pull request by dvdherron**
## Steps to test/reproduce
- Select the Help Walkthrough from the main dropdown list
- Click through the steps of the tour. 
_Please explain how to best reproduce the issue and/or test the changes locally (including the pages/URLs/views/states to review)._

## Show me
_Provide screenshots/animated gifs/videos if necessary._

# REMEMBER: Attach this PR to the Trello card

### CODE REVIEW

**Comment by dvdherron** [comment]
[As a new user, I want a walkthrough to introduce testing. (Help Walkthrough)](https://trello.com/c/q6wKx1xL/259-as-a-new-user-i-want-a-walkthrough-to-introduce-testing-help-walkthrough)

**Comment by dvdherron** [comment]
@jgerigmeyer @oluoluoxenfree I think this is mostly done. 

- There's a line that causes the dropdown to have less than 100% test coverage (use "istanbul ignore next" here too, like the Play walkthrough?)
- I think this is the first instance of a walkthrough that spans more than one page/view. Should this walkthrough  only start if someone is on the Tasks tab?  Or we route the user to the Tasks tab once the tour starts? 
- The fourth step ("Create Epic from Github Issue") is missing for now since we're still working on that feature. Thinking ahead, to get to that step we would have to switch back from the Tasks tab to the Epics tab. I did a quick glance on the Joystick site and didn't see any documentation about navigating to different views in between steps but I'll keep looking unless you all know of a better way to do this.

**Comment by jgerigmeyer** [comment]
>     * There's a line that causes the dropdown to have less than 100% test coverage (use "istanbul ignore next" here too, like the Play walkthrough?)

Yeah, feel free to ignore this one just like the Play walkthrough. No need to have individual tests just to trigger each of these identical cases.

>     * I think this is the first instance of a walkthrough that spans more than one page/view. Should this walkthrough  only start if someone is on the Tasks tab?  Or we route the user to the Tasks tab once the tour starts?

Good call; you're totally correct. I think we want the tour itself to control the selected tab while the tour is running. I pushed some code to start allowing this; check it out and see what you think. Basically I added an optional `onBeforeStep` callback that gets called with the step index before each step. That should work when we add the new GitHub Issues btn as well.

>     * The fourth step ("Create Epic from Github Issue") is missing for now since we're still working on that feature. Thinking ahead, to get to that step we would have to switch back from the Tasks tab to the Epics tab. I did a quick glance on the Joystick site and didn't see any documentation about navigating to different views in between steps but I'll keep looking unless you all know of a better way to do this.

See above 👍

**Comment by dvdherron** [comment]
@jgerigmeyer Nice. Still reading through it to see exactly how the code works but this functionally works great 👍🏽 🙏🏽

**Comment by jgerigmeyer** [comment]
@dvdherron I think this is done, ready for us to do code review together?

One minor thing I notice, would it be possible to enforce a consistent width for the Epics table columns (even when empty) like we do for Tasks table columns? cc @stacyk 

Screen Shot 2021-09-10 at 12 50 11 PM
Screen Shot 2021-09-10 at 12 50 22 PM

**Comment by dvdherron** [comment]
@jgerigmeyer Sounds good. How about a review on Monday? I'll add something to the calendar. And I'll get to the column spacing issue then too if Stacy doesn't fix it today.

**Comment by dvdherron** [comment]
I think this achieves the consistency you mentioned above @jgerigmeyer . The columns stay this size whether there is content or not. We can play around with the sizes if this doesn't work. 

The spacing is a little different since those last three columns won't really ever grow so wide. 

Empty
image
 
With content
image

If we decide to make the Tasks or Collaborator columns wider we would have to center or left-align those numbers.


With wider Task column
image

**Review by jgerigmeyer — APPROVED** [review]

**Comment by jgerigmeyer** [comment]
@stacyk This is ready for your review.

**Review by stacyk — APPROVED** [review]
@dvdherron Everything in this branch looks great.

**Pull request merged**
