### PR TITLE
[clean-up-devhub] Clean up user interactions with scratch orgs.

### PR DESCRIPTION
**Pull request by jgerigmeyer**
## Cute animal pic
_Because everyone likes pictures of animals._

clownfish

## Link to Trello card (if applicable)
_If this PR relates to a Trello card, don't forget to reference this PR on the card as well._

https://trello.com/c/dZtQ9YH9

## Description
_The commit messages say what you did; this should explain why and how._

- Require SF auth to re-check scratch org for unsaved changes.
- Do not require Dev Hub for capturing changes from a scratch org.

## Steps to test/reproduce
_Please explain how to best reproduce the issue and/or test the changes locally._

1. Create a scratch org with unsaved changes.
2. Log in with a SF org that does not have Dev Hub enabled.
3. Capture those changes. [It now works.]
4. Disconnect from SF and attempt to check for unsaved changes. [It now asks for SF connection first.]

---

## Reviewer tasks:

- [ ] Pulled branch and ran code locally (or viewed on preview deployment, if applicable)
- [ ] Reproduced the issue to review in the browser
- [ ] Reviewed code
- [ ] Updated Trello card (if applicable)

### CODE REVIEW

**Comment by davisagli** [comment]
@jgerigmeyer why are we requiring a dev hub connection to capture changes? that's an interaction with the scratch org only

**Comment by jgerigmeyer** [comment]
> @jgerigmeyer why are we requiring a dev hub connection to capture changes? that's an interaction with the scratch org only

@davisagli 🤔 Quite the opposite, in fact. We were before, but with this PR we are no longer requiring Dev Hub in order to capture changes.

**Comment by davisagli** [comment]
@jgerigmeyer but that sounds like the opposite of what I see in the PR description and steps to test? i.e. "Require SF auth to re-check scratch org for unsaved changes.", "Disconnect from SF and attempt to check for unsaved changes. [It now asks for SF connection first.]"

**Comment by davisagli** [comment]
@jgerigmeyer okay, let's talk about it

**Comment by jgerigmeyer** [comment]
Merging this; further cleanup coming in a separate PR.

**Pull request merged**
