### PR TITLE
Set GH_TOKEN on deploy-storybook job

### PR DESCRIPTION
**Pull request by jerivas**
## Description
https://github.com/storybookjs/storybook-deployer/issues/77

### CODE REVIEW

**Comment by jerivas** [comment]
Hold on, I also need to fix the concurrency issue. Right now only one job is executing for a given branch, instead of one of each kind

**Comment by jerivas** [comment]
I think it worked! https://github.com/oddbird/Metecho/runs/6313978941?check_suite_focus=true

**Comment by jerivas** [comment]
[Deploy Storybook docs via GH action on pushes to main branch.](https://trello.com/c/dwNddOEN/361-deploy-storybook-docs-via-gh-action-on-pushes-to-main-branch)

**Review by jgerigmeyer — APPROVED** [review]
🎉

**Pull request merged**
