### PR TITLE
[storybook RemoveUser]

### PR DESCRIPTION
**Pull request by dvdherron**
## Cute animal pic
image

_Because everyone likes pictures of [animals](https://unsplash.com/t/animals)._

## Link to Trello card (if applicable)
_If this PR relates to a Trello card, don't forget to reference this PR on the card as well._
https://trello.com/c/4haqWUTc/13-metecho-epics-confirmremoveusermodal

## Description
_The commit messages say what you did; this should explain why and/or how._
- [ x] Description is in Trello card

## Steps to test/reproduce
_Please explain how to best reproduce the issue and/or test the changes locally (including the pages/URLs/views/states to review)._
Under the Epics section, see the Docs and Example pages. 

## Show me
_Provide screenshots/animated gifs/videos if necessary._
image

### CODE REVIEW

**Comment by dvdherron** [comment]
@jgerigmeyer @duggiemitchell 
What am I missing to make the text dynamically say "users" instead of "user" if there are more than one `GitHubUsers`?

**Comment by dvdherron** [comment]
[Metecho epics › confirmRemoveUserModal](https://trello.com/c/4haqWUTc/13-metecho-epics-confirmremoveusermodal)

**Comment by jgerigmeyer** [comment]
> What am I missing to make the text dynamically say "users" instead of "user" if there are more than one `GitHubUsers`?

@dvdherron Hm, probably something related to the i18n translation files. I can take a look today.

**Review by jgerigmeyer — APPROVED** [review]

**Review by duggiemitchell — APPROVED** [review]

**Review by stacyk — APPROVED** [review]
This looks good to me. Glad we are including a "View example link"  in these as my eye went there right after reading the text.

Love the ant photo. I'm a big fan of taking photos of bugs/insects close up when I can.

**Pull request merged**
